appname:            'BaNG'
layout:             'main'
server:             '0.0.0.0'
template:           'template_toolkit'
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '<%'
    end_tag:   '%>'
show_errors:        1
error_template:     'error'
default_mime_type:  'text/plain'
logger:             'file'
logger_format:      '%t [%L] %m'
session: YAML
auth_ldap:
   server: 'ldaps://ldap.phys.ethz.ch'
   user_base_dn: 'ou1=People,ou=Physik Departement,o=ethz,c=ch'
   group_base_dn: 'ou1=Group,ou=Physik Departement,o=ethz,c=ch'
   username_attribute: 'uid'
   groupname_attribute: 'memberUid'
   groups_allowed: 'isg'
